# Generated by Django 3.1.3 on 2020-11-30 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caracteristica', models.CharField(max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'CaracteristicaProducto',
                'verbose_name_plural': 'CaracteristicasProductos',
                'ordering': ['caracteristica'],
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, null=True)),
                ('descripcion', models.CharField(max_length=60, null=True)),
                ('colorEtiqueta', models.CharField(max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'EstadoPedido',
                'verbose_name_plural': 'EstadosPedidos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoTurno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, null=True)),
                ('descripcion', models.CharField(max_length=60, null=True)),
                ('colorEtiqueta', models.CharField(max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Estado Turno',
                'verbose_name_plural': 'Estados Turnos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, null=True)),
                ('apellido', models.CharField(max_length=60, null=True)),
                ('fecha_nac', models.CharField(max_length=10, null=True)),
                ('sexo', models.CharField(max_length=1, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medico',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, null=True)),
                ('apellido', models.CharField(max_length=60, null=True)),
                ('fecha_nac', models.CharField(max_length=10, null=True)),
                ('sexo', models.CharField(max_length=1, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDePago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'TipoDePago',
                'verbose_name_plural': 'TiposDePagos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='ValorCaracteristicaProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'ValorCaracteristicaProducto',
                'verbose_name_plural': 'ValorCaracteristicaProductos',
                'ordering': ['valor'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=10, null=True)),
                ('detalle', models.TextField(null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.estadoturno', verbose_name='EstadoTurno')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.medico', verbose_name='Medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, null=True)),
                ('descripcion', models.CharField(max_length=120, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('caracteristicaProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.caracteristicaproducto', verbose_name='CaracteristicaProducto')),
                ('valorCaracteristicaProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.valorcaracteristicaproducto', verbose_name='ValorCaracteristicaProducto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_finalizado', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.estadopedido', verbose_name='EstadoPedido')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.paciente', verbose_name='Paciente')),
                ('producto', models.ManyToManyField(to='home.Producto', verbose_name='Producto')),
                ('tipoDePago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipodepago', verbose_name='TipoDePago')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ObservacionPaciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.TextField(null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'ObservacionPaciente',
                'verbose_name_plural': 'ObservacionesPacientes',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='caracteristicaproducto',
            name='valor',
            field=models.ManyToManyField(to='home.ValorCaracteristicaProducto', verbose_name='ValorCaracteristicaProducto'),
        ),
    ]
