# Generated by Django 3.1.3 on 2020-11-09 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, null=True)),
                ('apellido', models.CharField(max_length=60, null=True)),
                ('fecha_nac', models.DateField(null=True)),
                ('sexo', models.CharField(max_length=1, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medico',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, null=True)),
                ('apellido', models.CharField(max_length=60, null=True)),
                ('fecha_nac', models.DateField(null=True)),
                ('sexo', models.CharField(max_length=1, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.medico', verbose_name='Medico')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nombre'],
            },
        ),
    ]
