# Generated by Django 3.1.3 on 2020-11-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
