# Generated by Django 3.1.3 on 2020-11-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201109_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionPaciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.TextField(null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.paciente', verbose_name='Paciente')),
            ],
        ),
    ]
