# Generated by Django 3.1.3 on 2020-11-12 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_observacionpaciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='medico',
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nac', models.CharField(max_length=10, null=True)),
                ('detalle', models.TextField(null=True)),
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.medico')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.paciente')),
            ],
        ),
    ]
