# Generated by Django 3.1.3 on 2020-11-12 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201112_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='fecha_nac',
            new_name='fecha',
        ),
    ]
